version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - DEBUG=1 # Kept for teaching purpose
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5434:5432'
volumes:
  postgres: